# Generated by Django 4.1.7 on 2023-05-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No title', max_length=35, null=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=7)),
                ('image', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('CPU_details', models.CharField(blank=True, default='Not Specified Yet', max_length=22)),
                ('GPU_details', models.CharField(blank=True, default='Not Specified Yet', max_length=22)),
                ('RAM_details', models.CharField(blank=True, default='Not Specified Yet', max_length=24)),
                ('Panel_details', models.CharField(blank=True, default='Not Specified Yet', max_length=25)),
                ('discount', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('responsible_Clients', models.IntegerField(default=0)),
                ('Authenticated_By', models.CharField(choices=[('Custom-Authentication', 'Custom-Authentication'), ('Google', 'Google'), ('Facebook', 'Facebook')], default=('Facebook', 'Facebook'), max_length=21)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
