# Generated by Django 4.1.7 on 2023-05-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsBase', '0003_alter_cart_clonedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Not Name', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='Not Last Name', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='ClonedProduct',
            field=models.ManyToManyField(blank=True, default=None, to='ProductsBase.product'),
        ),
    ]
