# Generated by Django 4.1.7 on 2023-05-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsBase', '0005_alter_user_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconsForFrontend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_code', models.CharField(max_length=35)),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Icons for Front-End',
            },
        ),
    ]
