# Generated by Django 4.1.7 on 2023-05-23 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsBase', '0007_threads_messages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='threads',
            options={'verbose_name_plural': 'User Threads'},
        ),
        migrations.RenameField(
            model_name='threads',
            old_name='accossiated_user1',
            new_name='associated_user1',
        ),
        migrations.RenameField(
            model_name='threads',
            old_name='accossiated_user2',
            new_name='associated_user2',
        ),
        migrations.AddField(
            model_name='messages',
            name='associated_thread',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ProductsBase.threads'),
        ),
    ]
