# Generated by Django 4.1.7 on 2023-05-23 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsBase', '0009_remove_threads_associated_user1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportStaff',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ProductsBase.user',),
        ),
    ]
