# Generated by Django 4.1.7 on 2023-05-23 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsBase', '0010_supportstaff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportstaff',
            options={'verbose_name_plural': 'Support Staff'},
        ),
        migrations.CreateModel(
            name='Threads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Layercode', models.CharField(max_length=20)),
                ('Responder_Staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Support_Member', to='ProductsBase.supportstaff')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Consumer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Threads',
            },
        ),
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('Sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('associated_thread', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ProductsBase.threads')),
            ],
            options={
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
