# Generated by Django 4.1.7 on 2023-07-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsBase', '0014_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_for_black',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='product',
            name='price_for_rose',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='product',
            name='price_for_silver',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
    ]
